services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "${REDIS_SERVICE_PORT:-6379}:${REDIS_SERVICE_PORT:-6379}"
    networks:
      - app-network
    volumes:
      - redis_data:/data  # Volume cho Redis (nếu cần lưu trữ)

  notification-service:
    build:
      context: .
      dockerfile: ./services/notification-service/Dockerfile
    container_name: notification-service
    env_file: .env
    ports:
      - "${NOTIFICATION_SERVICE_PORT}:${NOTIFICATION_SERVICE_PORT}"
    volumes:
      - ./services/notification-service:/usr/src/app
      - ./shared:/usr/src/app/shared
      - /usr/src/app/node_modules
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - app-network
    depends_on:
      - redis

  auth-service:
    build:
      context: .
      dockerfile: ./services/auth-service/Dockerfile
    container_name: auth-service
    env_file: .env
    ports:
      - "${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}"
    volumes:
      - ./services/auth-service:/usr/src/app
      - ./shared:/usr/src/app/shared
      - /usr/src/app/node_modules
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - app-network
    depends_on:
      - redis

  user-service:
    build:
      context: .
      dockerfile: ./services/user-service/Dockerfile
    container_name: user-service
    env_file: .env
    ports:
      - "${USER_SERVICE_PORT}:${USER_SERVICE_PORT}"
    volumes:
      - ./services/user-service:/usr/src/app
      - ./shared:/usr/src/app/shared
      - /usr/src/app/node_modules
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - app-network
    depends_on:
      - redis

  post-service:
    build:
      context: .
      dockerfile: ./services/post-service/Dockerfile
    container_name: post-service
    env_file: .env
    ports:
      - "${POST_SERVICE_PORT}:${POST_SERVICE_PORT}"
    volumes:
      - ./services/post-service:/usr/src/app
      - ./shared:/usr/src/app/shared
      - /usr/src/app/node_modules
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - app-network
    depends_on:
      - redis

  websocket-service:
    build:
      context: .
      dockerfile: ./services/websocket-service/Dockerfile
    container_name: websocket-service
    env_file: .env
    ports:
      - "${WS_SERVICE_PORT}:${WS_SERVICE_PORT}"
    volumes:
      - ./services/websocket-service:/usr/src/app
      - ./shared:/usr/src/app/shared
      - /usr/src/app/node_modules
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - WS_PORT=${WS_SERVICE_PORT}
    networks:
      - app-network
    depends_on:
      - redis

  moderation-service:
    build:
      context: .
      dockerfile: ./services/moderation-service/Dockerfile
    container_name: moderation-service
    env_file: .env
    ports:
      - "${MODERATION_SERVICE_PORT}:${MODERATION_SERVICE_PORT}"
    volumes:
      - ./services/moderation-service:/usr/src/app
      - ./shared:/usr/src/app/shared
      - /usr/src/app/node_modules
      - cache_volume:/root/.cache  # Gắn volume cho cache
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - app-network
    depends_on:
      - redis

networks:
  app-network:
    driver: bridge

volumes:
  cache_volume:  # Định nghĩa volume cho cache
  redis_data:    # Volume cho Redis
