version: '3.8'

services:
  user-service:
    build:
      context: .
      dockerfile: ./services/user-service/Dockerfile
    container_name: user-service
    env_file: .env
    ports:
      - "${USER_SERVICE_PORT}:${USER_SERVICE_PORT}"
    volumes:
      - ./services/user-service:/usr/src/app
      - ./shared:/usr/src/app/shared
      - /usr/src/app/node_modules
    networks:
      - app-network

  post-service:
    build:
      context: .
      dockerfile: ./services/post-service/Dockerfile
    container_name: post-service
    env_file: .env
    ports:
      - "${POST_SERVICE_PORT}:${POST_SERVICE_PORT}"
    volumes:
      - ./services/post-service:/usr/src/app
      - /usr/src/app/node_modules
      - ./shared:/usr/src/app/shared
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
