version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "${REDIS_SERVICE_PORT}:${REDIS_SERVICE_PORT}"
    networks:
      - app-network
      
  notification-service:
    build:
      context: . 
      dockerfile: ./services/notification-service/Dockerfile  # Cấu hình giống auth-service
    container_name: notification-service  # Đặt tên cho container
    env_file: .env
    ports:
      - "${NOTIFi_SERVICE_PORT}:${NOTIFi_SERVICE_PORT}"
    volumes:
      - ./services/notification-service:/usr/src/app
      - ./shared:/usr/src/app/shared
      - /usr/src/app/node_modules
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - app-network

  auth-service:
    build:
      context: . 
      dockerfile: ./services/auth-service/Dockerfile
    container_name: auth-service
    env_file: .env
    ports:
      - "${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}"
    volumes:
      - ./services/auth-service:/usr/src/app
      - ./shared:/usr/src/app/shared
      - /usr/src/app/node_modules
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - app-network

  user-service:
    build:
      context: . 
      dockerfile: ./services/user-service/Dockerfile
    container_name: user-service
    env_file: .env
    ports:
      - "${USER_SERVICE_PORT}:${USER_SERVICE_PORT}"
    volumes:
      - ./services/user-service:/usr/src/app
      - ./shared:/usr/src/app/shared
      - /usr/src/app/node_modules
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - app-network

  post-service:
    build:
      context: . 
      dockerfile: ./services/post-service/Dockerfile
    container_name: post-service
    env_file: .env
    ports:
      - "${POST_SERVICE_PORT}:${POST_SERVICE_PORT}"
    volumes:
      - ./services/post-service:/usr/src/app
      - ./shared:/usr/src/app/shared
      - /usr/src/app/node_modules
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - app-network

  websocket-service:  # Đảm bảo có khoảng trắng trước dòng này
    build:
      context: . 
      dockerfile: ./services/websocket-service/Dockerfile  # Đường dẫn tới Dockerfile cho WebSocket service
    container_name: websocket-service
    env_file: .env
    ports:
      - "${WS_SERVICE_PORT}:${WS_SERVICE_PORT}"  # Cổng cho WebSocket service
    volumes:
      - ./services/websocket-service:/usr/src/app
      - ./shared:/usr/src/app/shared
      - /usr/src/app/node_modules
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - WS_PORT=${WS_SERVICE_PORT}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
